version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: prreviewbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: codereviewdb
      POSTGRES_USER: rachit
      POSTGRES_PASSWORD: rachit123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: prreviewbot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

# docker exec -it prreviewbot-postgres psql -U rachit -d codereviewdb -> use this for interacting with postgres
# \dt  ->getting inside postgres container
# \q  ->for exit

# docker exec -it prreviewbot-redis redis-cli  -> verify redis and then run ping