apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  GEMINI_API_KEY: "your_gemini_api_key"
  GITHUB_TOKEN: "your_github_token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prreviewbot-backend
  labels:
    app: prreviewbot-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prreviewbot-backend
  template:
    metadata:
      labels:
        app: prreviewbot-backend
    spec:
      containers:
        - name: backend
          image: prreviewbot-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/codereviewdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "rachit"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "rachit123"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          envFrom:
            - secretRef:
                name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: prreviewbot-backend
  ports:
    - port: 8080
      targetPort: 8080
